name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build and Test OTP ${{matrix.pair.otp}} / Elixir ${{matrix.pair.elixir}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pair:
          - otp: 23
            elixir: "1.10"
          - otp: 23
            elixir: "1.11"
          - otp: 23
            elixir: "1.12"
          - otp: 24
            elixir: "1.12"
          - otp: 24
            elixir: "1.13"
          - otp: 25
            elixir: "1.13"
          - otp: 24
            elixir: "1.14"
          - otp: 25
            elixir: "1.14"

    env:
      MIX_ENV: test
      ImageOS: ubuntu20 # equivalent to runs-on ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{matrix.pair.elixir}} # Define the elixir version [required]
          otp-version: ${{matrix.pair.otp}} # Define the OTP version [required]

      - uses: actions/cache@v1
        id: deps-cache
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ matrix.pair.otp }}-${{ matrix.pair.elixir }}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - uses: actions/cache@v1
        id: build-cache
        with:
          path: _build
          key: ${{ runner.os }}-build-${{ matrix.pair.otp }}-${{ matrix.pair.elixir }}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - name: Install dependencies
        run: |
          mix deps.clean --all
          mix deps.get

      - name: Run tests
        run: |
          MIX_ENV=test elixir -S mix test
